"""Pagouro BE showcase, jigsaw batch 2 (2026-10-06): captions toward a year of daily puzzles.

Eric: "I'd be happy knowing we have a years worth of pictures." The game has 160; a year is 365, so batch 2 aims to
keep about 205. Batch 1 kept 89 of 134 captions (66 %), so this list has 300.

The new pictures take the daily calendar from 2026-11-17 (when the first 160-day cycle would start repeating) to
mid-June 2027, so each caption carries a SEASON and the calendar places winter pictures in December to February,
spring ones in March to May, early summer in June; "any" fills the gaps. The first 160 are thin on winter (1),
holidays and animals, so those get the most.

Same rules as batch 1: no words in any picture; faces must be right (people captions get 12 seeds, others 8, and
fewer people overall because faces fail most); no living person, no trademark, no drinking or smoking; nothing
already in the game (checked against pictures.json by the script).

    python scripts/showcase_jigsaw_b2_prompts.py  ->  showcase/jigsaw_b2/captions.jsonl
"""
import io, json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), "showcase", "jigsaw_b2")
GAME_PICTURES = r"C:\Users\Eric Wade\PAGOURO_PLAY\jigsaw\art\be\pictures.json"
PREFIX = "belleposter, Belle Epoque lithograph poster, "
NEGATIVE = ("photograph, photo, 3d render, blurry, watermark, text, lettering, words, caption, title, modern, "
            "gradient, deformed face, distorted face, asymmetrical eyes, extra fingers, extra limbs, "
            "cigarette, smoking, wine glass, bottle")

P, N = True, False
W, S, U, A = "winter", "spring", "summer", "any"
# (season, category, people?, caption)
CAPTIONS = [
    # ---- winter: snow, holidays, the new year (December to February) ----
    (W, "winter", N, "a Christmas market of wooden stalls under snow, lit by lanterns at dusk"),
    (W, "winter", P, "skaters gliding on a frozen lake beneath snowy pine trees"),
    (W, "winter", N, "a horse-drawn sleigh crossing a snowy meadow toward a village church"),
    (W, "winter", N, "a decorated Christmas tree with candles in a grand hall"),
    (W, "winter", N, "an alpine village under deep snow with smoke rising from chimneys"),
    (W, "winter", P, "a chestnut seller with a glowing brazier on a snowy street corner"),
    (W, "winter", N, "a frozen canal with skaters between tall gabled houses"),
    (W, "winter", N, "a snow-covered castle on a hill under a starry winter sky"),
    (W, "winter", N, "a robin perched on a snowy branch with red berries"),
    (W, "winter", N, "a steam train crossing a snowy mountain pass"),
    (W, "winter", N, "a lamplit street of shop windows full of toys on a snowy evening"),
    (W, "winter", P, "a skier in a red jacket on a snowy slope above an alpine valley"),
    (W, "winter", N, "a toboggan run winding down a snowy hillside past fir trees"),
    (W, "winter", N, "a cozy fireside with stockings hung on a carved mantelpiece"),
    (W, "winter", N, "a gingerbread house and sweets on a festive table"),
    (W, "winter", N, "a wreath of holly and pine cones on a green wooden door"),
    (W, "winter", N, "fireworks over a snowy city on New Year's night"),
    (W, "winter", P, "couples waltzing in a chandeliered ballroom on New Year's Eve"),
    (W, "winter", N, "a snowy forest at moonlight with a deer among the trees"),
    (W, "winter", N, "a mountain hotel with lit windows below snowy peaks at dusk"),
    (W, "winter", N, "a frozen waterfall of blue ice in a mountain gorge"),
    (W, "winter", N, "a snowy village square with a tall decorated fir tree"),
    (W, "winter", N, "a pair of white swans on a dark winter river with snowy banks"),
    (W, "winter", N, "a red cardinal bird on a snowy fence post"),
    (W, "winter", N, "a lighthouse in a snowstorm with its beam shining"),
    (W, "winter", N, "a snow-covered garden with a stone fountain and clipped hedges"),
    (W, "winter", P, "children building a snowman in a village lane"),
    (W, "winter", N, "an ice palace glowing with lanterns at night"),
    (W, "winter", N, "a train station in snow with a steaming locomotive and lamplight"),
    (W, "winter", N, "a sleigh full of wrapped presents in a moonlit forest"),
    (W, "winter", N, "snowy rooftops of an old town with church spires at dawn"),
    (W, "winter", N, "a winter bouquet of white hellebores and holly in a silver vase"),
    (W, "winter", N, "a frosted window with ice patterns and a candle glowing behind it"),
    (W, "winter", N, "an owl on a snowy branch under a full moon"),
    (W, "winter", P, "a curling match on a frozen lake below mountains"),
    (W, "winter", N, "a snowy bridge over a frozen river in a park with lamp posts"),
    (W, "winter", N, "a mountain chapel half buried in snow"),
    (W, "winter", N, "a snowy pine forest at sunrise with pink light on the snow"),
    (W, "winter", N, "an ice rink in a city park lit by strings of lights at night"),
    (W, "winter", N, "a red sleigh outside a timber chalet with snowy peaks behind"),
    (W, "winter", N, "a festive table set with candles, oranges and pine branches"),
    (W, "winter", N, "a squirrel on a snowy tree branch with acorns"),
    (W, "winter", N, "a winter harbor with icy fishing boats and snowy quays"),
    (W, "winter", P, "a lamplighter on a ladder lighting a gas lamp on a snowy evening"),
    (W, "winter", N, "a snowy vineyard with rows of bare vines and a stone farmhouse"),
    (W, "winter", N, "a carousel under snow in a quiet park"),
    (W, "winter", N, "an arctic ship trapped in ice under the northern lights"),
    (W, "winter", N, "the northern lights over a snowy fjord"),
    (W, "winter", N, "polar bears on an ice floe under a pale sky"),
    (W, "winter", N, "a husky dog team pulling a sled across snow"),
    (W, "winter", N, "a snowy Paris street with the Eiffel Tower in the distance"),
    (W, "winter", N, "a winter garden conservatory full of orange trees with snow outside"),
    (W, "winter", P, "a woman in a fur-trimmed cape walking under snowy chestnut trees"),
    (W, "winter", N, "a stone bridge in Prague under snow with statues along it"),
    (W, "winter", N, "a Viennese palace in snow with a frozen pond in front"),
    (W, "winter", N, "a snowy mountain railway with a red train climbing a viaduct"),
    (W, "winter", N, "a Christmas wreath of oranges, cinnamon and ribbon on a white background"),
    (W, "winter", N, "a hot chocolate pot and cups beside a frosty window"),
    (W, "winter", N, "an angel-shaped weathervane on a snowy church spire"),
    (W, "winter", N, "a toy shop window with a rocking horse and dolls"),
    (W, "winter", N, "a snowy country lane with a horse and cart at dusk"),
    (W, "winter", N, "a snowy owl flying over a white field"),
    (W, "winter", P, "carol singers with lanterns at a doorway in the snow"),
    (W, "winter", N, "a candlelit cathedral interior at midnight"),
    (W, "winter", N, "a mountain lake frozen white below snowy peaks under a blue sky"),
    (W, "winter", N, "a red mailbox and a snowy cottage gate with a wreath"),
    (W, "winter", N, "a Valentine bouquet of red roses and lace in a heart-shaped basket"),
    (W, "winter", N, "a masked carnival ball in Venice with costumes and candlelight"),
    (W, "winter", P, "a harlequin and a columbine in carnival costumes on a stage"),
    (W, "winter", N, "Venetian carnival masks with feathers on a velvet cloth"),

    # ---- spring: blossom, rain, new life (March to May) ----
    (S, "spring", N, "an orchard of white apple blossom with a thatched cottage"),
    (S, "spring", N, "a field of tulips in red, yellow and pink stripes toward a windmill"),
    (S, "spring", N, "a blue carpet of bluebells under beech trees in a wood"),
    (S, "spring", N, "lambs in a green meadow with a stone wall and blossom trees"),
    (S, "spring", P, "children flying kites on a windy hill"),
    (S, "spring", N, "a spring shower over a town square with umbrellas and puddles"),
    (S, "spring", N, "a basket of painted eggs among daffodils"),
    (S, "spring", N, "a bird's nest with blue eggs on a blossoming branch"),
    (S, "spring", N, "a magnolia tree in full pink bloom in a city park"),
    (S, "spring", N, "a stream through a spring meadow of buttercups"),
    (S, "spring", N, "a pair of swallows over a farmhouse roof"),
    (S, "spring", N, "lilies of the valley in a small porcelain pot"),
    (S, "spring", N, "a rainbow over green hills after a spring storm"),
    (S, "spring", P, "a flower market under awnings with buckets of tulips and a seller in an apron"),
    (S, "spring", N, "almond trees in blossom on a terraced hillside by the sea"),
    (S, "spring", N, "a hare sitting among spring flowers in a meadow"),
    (S, "spring", N, "a garden gate covered in climbing pink roses"),
    (S, "spring", N, "a country church surrounded by blooming cherry trees"),
    (S, "spring", N, "ducklings following a duck across a village pond"),
    (S, "spring", N, "a hyacinth bowl of blue and white flowers on a windowsill"),
    (S, "spring", N, "a garden path lined with tulips leading to a glasshouse"),
    (S, "spring", P, "a woman with a parasol walking through an orchard in blossom"),
    (S, "spring", N, "a horse ploughing a field in spring with gulls behind"),
    (S, "spring", N, "a crocus lawn in purple and gold beneath bare trees"),
    (S, "spring", N, "a canal in Amsterdam in spring with blossom trees and houseboats"),
    (S, "spring", N, "a dovecote with white doves in a spring garden"),
    (S, "spring", N, "a butterfly on a lilac branch"),
    (S, "spring", N, "a maypole with colored ribbons on a village green"),
    (S, "spring", P, "a girl gathering daffodils in a meadow"),
    (S, "spring", N, "a kingfisher on a reed by a clear stream"),
    (S, "spring", N, "a Japanese cherry tree over a stone lantern and a pond"),
    (S, "spring", N, "spring rain on a quiet Paris street with blossoming trees"),
    (S, "spring", N, "a hillside of yellow gorse above the sea"),
    (S, "spring", N, "a garden of irises in purple and white beside a pond"),
    (S, "spring", N, "foals beside their mother in a green paddock"),
    (S, "spring", N, "a beehive in an orchard with bees among blossom"),
    (S, "spring", N, "an old stone bridge over a river in spring with willow trees"),
    (S, "spring", N, "a wicker basket of spring vegetables and radishes on a table"),
    (S, "spring", N, "a spring forest with a carpet of white wood anemones"),
    (S, "spring", N, "a peony garden in pink and white beside a summerhouse"),
    (S, "spring", P, "a gardener planting seedlings in a walled garden"),
    (S, "spring", N, "a greenhouse of orchids in many colors"),
    (S, "spring", N, "a stork nest on a chimney above a village"),
    (S, "spring", N, "rows of tulips in a botanical garden with a glass palace behind"),
    (S, "spring", N, "a chestnut tree in white candles of blossom over a cafe"),
    (S, "spring", N, "a spring morning over the Seine with blossoming trees on the quay"),
    (S, "spring", N, "a field of yellow rapeseed under a big blue sky"),
    (S, "spring", N, "a heron standing in a misty marsh at dawn"),
    (S, "spring", N, "a puppy asleep in a basket of spring flowers"),
    (S, "spring", N, "a primrose bank beside a woodland stream"),
    (S, "spring", P, "a couple walking under a blossom-covered avenue"),
    (S, "spring", N, "an April sky of white clouds over a patchwork of fields"),
    (S, "spring", N, "a rabbit among carrots in a kitchen garden"),
    (S, "spring", N, "the Tower Bridge in London on a spring morning with boats on the Thames"),
    (S, "spring", N, "a wisteria-covered house by a canal"),
    (S, "spring", N, "a vase of ranunculus in coral and pink"),
    (S, "spring", N, "a garden swing hanging from an apple tree in blossom"),
    (S, "spring", N, "a mountain meadow full of spring gentians below snowy peaks"),
    (S, "spring", N, "a pair of goldfinches on a thistle"),
    (S, "spring", P, "a painter with an easel in a blooming orchard"),
    (S, "spring", N, "a Dutch flower stall of tulips beside a canal bridge"),
    (S, "spring", N, "a terrace of lemon trees in pots in a Mediterranean garden"),
    (S, "spring", N, "a cascade of white roses over a stone wall"),
    (S, "spring", N, "a horse-drawn carriage through a park full of blossom"),
    (S, "spring", N, "a frog on a lily pad among spring reeds"),
    (S, "spring", N, "the Brandenburg Gate on a spring day with linden trees"),

    # ---- early summer (June): seaside, gardens, sport ----
    (U, "seaside", N, "striped bathing huts in a row on a sandy beach"),
    (U, "seaside", P, "children building sandcastles on a beach with buckets and spades"),
    (U, "seaside", N, "a seaside pier with a domed pavilion over blue water"),
    (U, "seaside", N, "a grand seaside hotel with balconies above a promenade"),
    (U, "seaside", N, "parasols on a beach in red and white stripes"),
    (U, "seaside", N, "a Punch and Judy booth on a sunny beach"),
    (U, "seaside", P, "bathers in striped suits wading into the sea"),
    (U, "seaside", N, "rock pools at low tide with starfish and shells"),
    (U, "seaside", N, "a sailing dinghy pulled up on a beach beside dunes"),
    (U, "sport", P, "a tennis match on a grass court with spectators in white"),
    (U, "sport", P, "a rowing eight racing on a river past cheering crowds"),
    (U, "sport", N, "a horse race on a green track with jockeys in bright silks"),
    (U, "sport", P, "a croquet game on a lawn with players in summer clothes"),
    (U, "sport", N, "a polo match with horses galloping on a green field"),
    (U, "summer", N, "a hay meadow with haystacks under a summer sky"),
    (U, "summer", N, "a summer garden party with tables under a white marquee"),
    (U, "summer", N, "a lily pond with a stone bridge on a summer afternoon"),
    (U, "summer", N, "strawberries in a basket with cream and a lace cloth"),
    (U, "summer", N, "a riverside inn with flower boxes and a boat landing"),
    (U, "summer", N, "a midsummer bonfire on a beach at dusk"),
    (U, "summer", P, "a girl in a straw hat on a swing in a summer garden"),
    (U, "summer", N, "a meadow of daisies and clover with butterflies"),
    (U, "summer", N, "a white sailboat on a calm sea at sunset"),
    (U, "summer", N, "a bandstand in a park with an audience on deck chairs"),
    (U, "summer", N, "an ice cream cart under a striped awning in a park"),
    (U, "summer", N, "hollyhocks against a cottage wall in summer"),
    (U, "summer", N, "a rowing boat full of flowers on a lake"),
    (U, "summer", N, "a summer storm over a wheat field with lightning in the distance"),
    (U, "summer", P, "a family picnic in a meadow with a red checked cloth"),
    (U, "summer", N, "dragonflies over a pond of water lilies"),

    # ---- any season: animals, birds, cities, travel, music, still life, science ----
    (A, "animals", N, "a tabby cat asleep in a sunny window"),
    (A, "animals", N, "a dachshund in a red collar sitting on a doorstep"),
    (A, "animals", N, "a white horse galloping along a beach"),
    (A, "animals", N, "an owl on a branch with large golden eyes"),
    (A, "animals", N, "a stag with great antlers in a misty glen"),
    (A, "animals", N, "a family of foxes at the edge of a wood"),
    (A, "animals", N, "a hedgehog among autumn leaves"),
    (A, "animals", N, "two kittens playing with a ball of yarn"),
    (A, "animals", N, "a parrot with bright feathers on a perch"),
    (A, "animals", N, "a pair of flamingos in a shallow lagoon"),
    (A, "animals", N, "a lion resting on a rock at sunset"),
    (A, "animals", N, "an elephant with a decorated saddle cloth"),
    (A, "animals", N, "a zebra on a golden savanna under acacia trees"),
    (A, "animals", N, "a giraffe beside a tall acacia tree"),
    (A, "animals", N, "a tiger walking through tall jungle grass"),
    (A, "animals", N, "a sheepdog guarding a flock on a hillside"),
    (A, "animals", N, "a goat on a rocky mountain ledge"),
    (A, "animals", N, "cows in a meadow with a bell tower behind"),
    (A, "animals", N, "a pair of horses pulling a hay cart along a lane"),
    (A, "animals", N, "a goldfish bowl on a table by a window"),
    (A, "animals", N, "a Siamese cat on a silk cushion"),
    (A, "animals", N, "a greyhound running across a meadow"),
    (A, "animals", N, "a spaniel with a ball in a garden"),
    (A, "animals", N, "a tortoise in a garden of clover"),
    (A, "animals", N, "a squirrel eating a nut on a park bench"),
    (A, "animals", N, "a badger at the mouth of its burrow at dusk"),
    (A, "animals", N, "a seal on a rock by a lighthouse"),
    (A, "animals", N, "dolphins leaping beside a sailing ship"),
    (A, "animals", N, "a whale surfacing beside a fishing boat"),
    (A, "animals", N, "a sea turtle swimming in clear blue water"),
    (A, "animals", N, "a camel caravan crossing golden dunes"),
    (A, "animals", N, "a panda eating bamboo"),
    (A, "animals", N, "a koala in a eucalyptus tree"),
    (A, "animals", N, "a kangaroo in red grassland at sunrise"),
    (A, "animals", N, "a penguin colony on an icy shore"),
    (A, "animals", N, "a bear fishing in a rushing river"),
    (A, "animals", N, "an otter floating on its back in a river"),
    (A, "animals", N, "a black and white cat on a garden wall"),
    (A, "animals", N, "a basket of puppies in a farmhouse kitchen"),
    (A, "animals", N, "a donkey with flower baskets in a village street"),
    (A, "birds", N, "a toucan on a jungle branch"),
    (A, "birds", N, "a barn owl in flight at dusk"),
    (A, "birds", N, "hummingbirds at red trumpet flowers"),
    (A, "birds", N, "a pair of mandarin ducks on a pond"),
    (A, "birds", N, "a golden pheasant in a woodland clearing"),
    (A, "birds", N, "a heron catching a fish in reeds"),
    (A, "birds", N, "white cockatoos on a branch"),
    (A, "birds", N, "a blue jay on an oak branch"),
    (A, "birds", N, "seagulls over a fishing harbor"),
    (A, "birds", N, "a pelican on a wooden post by the sea"),
    (A, "birds", N, "a flock of geese flying over marshland at sunset"),
    (A, "birds", N, "an eagle soaring above mountain peaks"),
    (A, "insects", N, "a swallowtail butterfly on a purple thistle"),
    (A, "insects", N, "a collection of colorful butterflies arranged in rows"),
    (A, "insects", N, "a dragonfly with shimmering wings on a reed"),
    (A, "insects", N, "a ladybird on a green leaf with dewdrops"),
    (A, "cities", N, "Venice's Grand Canal with gondolas and palaces at sunset"),
    (A, "cities", N, "the Doge's Palace and a lagoon full of boats"),
    (A, "cities", N, "a Viennese opera house at night with carriages"),
    (A, "cities", N, "Prague's old town square with its clock tower"),
    (A, "cities", N, "Big Ben and the Houses of Parliament by the Thames at dusk"),
    (A, "cities", N, "Barcelona's harbor with sailing ships and a column"),
    (A, "cities", N, "a Lisbon tram climbing a steep street of tiled houses"),
    (A, "cities", N, "Florence cathedral dome above red rooftops"),
    (A, "cities", N, "Rome's Colosseum at sunset with umbrella pines"),
    (A, "cities", N, "the Bosphorus with domes and minarets at dawn"),
    (A, "cities", N, "Budapest's parliament on the Danube at night"),
    (A, "cities", N, "Copenhagen's colorful harbor houses and sailboats"),
    (A, "cities", N, "Bruges canals with medieval houses and a bell tower"),
    (A, "cities", N, "St Petersburg palace on a river with golden spires"),
    (A, "cities", N, "Edinburgh castle on its rock above the city"),
    (A, "cities", N, "Seville's tower and orange trees in a sunny square"),
    (A, "cities", N, "the Brooklyn Bridge at sunset with sailboats below"),
    (A, "cities", N, "a New York avenue of early skyscrapers with horse carriages"),
    (A, "cities", N, "San Francisco hills with cable cars and the bay"),
    (A, "cities", N, "the Statue of Liberty with a steamship arriving in the harbor"),
    (A, "cities", N, "a Mississippi riverboat at a busy levee"),
    (A, "cities", N, "Rio's harbor with Sugarloaf Mountain at dusk"),
    (A, "cities", N, "Kyoto pagoda among maple trees"),
    (A, "cities", N, "Mount Fuji above a lake with a fishing boat"),
    (A, "cities", N, "Cairo's pyramids at sunset with camels"),
    (A, "cities", N, "a Moroccan courtyard with a fountain and blue tiles"),
    (A, "cities", N, "the Taj Mahal reflected in a long pool"),
    (A, "cities", N, "Athens' Acropolis above the city at golden hour"),
    (A, "cities", N, "a Swiss lake town with a covered wooden bridge"),
    (A, "cities", N, "Salzburg's fortress above the river at dawn"),
    (A, "cities", N, "Monte Carlo harbor with yachts and terraced gardens"),
    (A, "cities", N, "the Alhambra palace with its gardens and mountains"),
    (A, "cities", N, "a Paris rooftop view at night with chimneys and the moon"),
    (A, "cities", N, "the Louvre courtyard with fountains in sunlight"),
    (A, "cities", N, "Notre-Dame cathedral from the Seine at dawn"),
    (A, "cities", N, "the Paris Opera house grand staircase"),
    (A, "cities", N, "the Luxembourg Garden pond with toy sailboats"),
    (A, "cities", N, "a Paris metro entrance in curling green ironwork"),
    (A, "travel", N, "an ocean liner leaving port with streamers and tugs"),
    (A, "travel", N, "a luxury sleeping-car train crossing mountains at night"),
    (A, "travel", N, "a railway dining car set with white linen and flowers"),
    (A, "travel", N, "a steamship on the Nile passing palm trees"),
    (A, "travel", N, "a mountain cog railway climbing toward a glacier"),
    (A, "travel", N, "a vintage motor car touring a mountain road"),
    (A, "travel", N, "a seaplane landing on a lake beside a hotel"),
    (A, "travel", N, "a funicular climbing a green hillside above a lake"),
    (A, "travel", N, "steamer trunks and hatboxes on a station platform"),
    (A, "travel", N, "a lighthouse keeper's cottage on a rocky point"),
    (A, "travel", N, "a hot-air balloon over the pyramids"),
    (A, "travel", N, "a caravan of colorful gypsy wagons on a country road"),
    (A, "music", N, "a grand piano in a sunlit music room with open windows"),
    (A, "music", P, "a string quartet playing in a candlelit salon"),
    (A, "music", N, "a harp beside a window with velvet curtains"),
    (A, "music", P, "a brass band marching in a town square"),
    (A, "music", N, "a gramophone with a flower-shaped horn on a table"),
    (A, "music", P, "a ballerina in a white tutu on stage"),
    (A, "music", P, "a cellist playing in an empty concert hall"),
    (A, "music", N, "an organ with tall pipes in a cathedral"),
    (A, "food", N, "a bakery window with baguettes, croissants and tarts"),
    (A, "food", N, "a cheese shop with wheels of cheese stacked on shelves"),
    (A, "food", N, "a patisserie display of colorful macarons and cakes"),
    (A, "food", N, "a bowl of lemons and oranges on a blue tablecloth"),
    (A, "food", N, "a copper kitchen with pots and hanging herbs"),
    (A, "food", N, "a pumpkin harvest in a farmyard with a cart"),
    (A, "food", N, "a basket of mushrooms on a forest floor"),
    (A, "food", N, "a cherry orchard with ladders and full baskets"),
    (A, "food", N, "a tea set with a teapot of roses on a garden table"),
    (A, "food", N, "a spice market with heaps of colored spices"),
    (A, "stilllife", N, "a still life of seashells on a velvet cloth"),
    (A, "stilllife", N, "an antique globe and books on a desk by a window"),
    (A, "stilllife", N, "a bouquet of tulips in a pewter jug"),
    (A, "stilllife", N, "a bowl of cherries beside a silver teapot"),
    (A, "stilllife", N, "a mantel clock and candlesticks on a marble fireplace"),
    (A, "stilllife", N, "an hourglass, a quill and an open map"),
    (A, "science", N, "a planetarium dome with painted constellations"),
    (A, "science", N, "an observatory dome open to a starry sky"),
    (A, "science", N, "the moon over a sea with a sailing ship, its craters drawn large"),
    (A, "science", N, "a comet over a sleeping village"),
    (A, "science", N, "a botanist's table of pressed flowers and a magnifying glass"),
    (A, "science", N, "a large brass microscope on a laboratory bench"),
    (A, "science", N, "the planet Saturn with its rings over a desert"),
    (A, "science", N, "an early airplane in a workshop with engineers' tools"),
    (A, "science", N, "a hall of dinosaur skeletons in a natural history museum"),
    (A, "science", N, "a diving bell lowered into a green sea with fish around"),
    (A, "science", N, "a submarine exploring a coral reef"),
    (A, "science", N, "a solar eclipse over mountains"),
    (A, "nature", N, "a coral reef with tropical fish"),
    (A, "nature", N, "a jellyfish drifting in blue water"),
    (A, "nature", N, "a canyon of red rocks at sunset"),
    (A, "nature", N, "a volcano with a plume of smoke over the sea"),
    (A, "nature", N, "a giant redwood forest with sunbeams"),
    (A, "nature", N, "a tropical beach with palm trees and an outrigger canoe"),
    (A, "nature", N, "a desert oasis with palm trees and a pool"),
    (A, "nature", N, "a geyser erupting in a snowy valley"),
    (A, "nature", N, "a bamboo forest with a narrow path"),
    (A, "nature", N, "rice terraces on a green mountainside"),
    (A, "nature", N, "a glacier meeting the sea with icebergs"),
    (A, "nature", N, "a cave with glittering crystals and an underground lake"),
    (A, "nature", N, "a thunderstorm over the ocean at night"),
    (A, "nature", N, "a mountain stream over mossy stones in a forest"),
    (A, "nature", N, "a lake at sunrise with mist and a wooden dock"),
    (A, "nature", N, "cliffs with seabirds above a crashing sea"),
    (A, "nature", N, "a field of tall grasses with a lone oak tree"),
    (A, "nature", N, "an autumn maple forest in red and orange by a lake"),
    (A, "nature", N, "a harvest moon over golden wheat sheaves"),
    (A, "nature", N, "a misty valley with layered blue hills"),
    (A, "nature", N, "a starry night over a sleeping town"),
    (A, "fun", N, "a puppet theater with velvet curtains"),
    (A, "fun", N, "a toy train set circling a Christmas village"),
    (A, "fun", N, "a merry-go-round of carved animals at a seaside fair"),
    (A, "fun", N, "a Ferris wheel at an exhibition at night"),
    (A, "fun", N, "a magic lantern show with a glowing projected picture"),
    (A, "fun", P, "a tightrope walker high above a circus ring"),
    (A, "fun", N, "an elephant balancing on a drum in a circus ring"),
    (A, "fun", N, "a hall of mirrors at a fairground"),
    (A, "fun", N, "a boating lake with swan-shaped pedal boats"),
    (A, "fun", N, "a chess set mid-game by a fireplace"),
    (A, "fun", N, "a doll's house with every room furnished"),
    (A, "fun", N, "colorful kites over a seaside cliff"),
    (A, "people", P, "a fisherman mending nets on a quay"),
    (A, "people", P, "a woman in a wide hat feeding swans at a lake"),
    (A, "people", P, "a gentleman in a top hat walking a greyhound"),
    (A, "people", P, "a lady with a parasol on a garden bridge"),
    (A, "people", P, "a balloonist waving from a basket above fields"),
    (A, "people", P, "a woman reading on a garden bench under roses"),
    (A, "people", P, "a young man rowing a lady across a lake"),
    (A, "people", P, "a dancer in a peacock-feather costume"),
    (A, "people", P, "a woman in a hat with flowers arranging a bouquet"),
    (A, "people", P, "a sailor coiling rope on a ship's deck"),
    (A, "people", P, "an aviator in goggles beside a biplane"),
    (A, "people", P, "a woman driving an open motor car with a scarf flying"),
    (A, "architecture", N, "an art nouveau doorway with stained glass and ironwork"),
    (A, "architecture", N, "a glass-roofed shopping arcade with mosaic floors"),
    (A, "architecture", N, "a grand railway station hall with a great clock"),
    (A, "architecture", N, "a palm house of curved glass in a winter garden"),
    (A, "architecture", N, "a lighthouse made of red brick on a sandbank"),
    (A, "architecture", N, "a windmill by a canal at sunset"),
    (A, "architecture", N, "a covered bridge over a forest river"),
    (A, "architecture", N, "a cathedral rose window glowing with color"),
    (A, "architecture", N, "a Venetian palazzo with balconies over a canal"),
    (A, "architecture", N, "an exhibition palace with domes and flags"),
    (A, "architecture", N, "a garden folly temple on a lake island"),
    (A, "architecture", N, "a spiral iron staircase in a lighthouse"),
]


def slug(c):
    w = re.sub(r"[^a-z0-9 ]", "", c.lower().replace("é", "e").replace("œ", "oe").replace("'", "")).split()
    stop = {"a", "an", "the", "of", "in", "on", "with", "and", "at", "by", "to", "over", "under", "above", "along",
            "through", "its", "from", "into", "past", "up", "down", "seen", "across", "between", "beside", "behind",
            "s"}
    return "-".join([x for x in w if x not in stop][:4])


def main():
    have = {p["caption"].lower() for p in json.load(io.open(GAME_PICTURES, encoding="utf-8"))}
    os.makedirs(OUT, exist_ok=True)
    seen = set()
    rows = []
    for i, (season, cat, people, cap) in enumerate(CAPTIONS, 1):
        assert cap.lower() not in have, ("already in the game", cap)
        s = slug(cap)
        assert s not in seen, ("duplicate slug", s)
        seen.add(s)
        rows.append({"number": i, "slug": s, "season": season, "category": cat, "caption": cap,
                     "prompt": PREFIX + cap, "negative": NEGATIVE, "people": people})
    with io.open(os.path.join(OUT, "captions.jsonl"), "w", encoding="utf-8", newline="\n") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
    n_p = sum(1 for r in rows if r["people"])
    by = {}
    for r in rows:
        by[r["season"]] = by.get(r["season"], 0) + 1
    print(f"{len(rows)} captions {by}, {n_p} with people (12 seeds), {len(rows) - n_p} without (8 seeds): "
          f"{n_p * 12 + (len(rows) - n_p) * 8} pictures")


if __name__ == "__main__":
    main()
